### ISSUE TITLE
你好，我有一些问题想要您解答一下

### ISSUE THREAD

**Issue by Aokye** [Yukiriri/OMCF#2]
我在windows-server2012R2中运行你的脚本，出现了无法跑脚本的问题，在你的经验总结中有些参数也不太清楚，想请问怎么联系你，望解答，谢谢！

**Comment by charliealexander73** [comment]
好兄弟，你最少把跑不了报错的屏幕截图贴出来给大家看下吧？你这样提问，大伙只能帮你去路边摊找人算一卦。

**Comment by Aokye** [comment]
添加好运行脚本后，跑脚本命令行窗口闪了一下就没了，提示内容是这个：
failed to lookup symbol:VirtualAlloc2
Error occurred during initialization of VM
ZGC requires Windows version 1803 or later
我用的系统是windows-server2012R2

**Comment by Aokye** [comment]
> 添加好运行脚本后，跑脚本命令行窗口闪了一下就没了，提示内容是这个： failed to lookup symbol:VirtualAlloc2 Error occurred during initialization of VM ZGC requires Windows version 1803 or later 我用的系统是windows-server2012R2

jdk是Liberica JDK21 64-bit

**Comment by Yukiriri** [comment]
报错当中有一段话“ZGC requires Windows version 1803 or later”已经说明了问题所在，启用ZGC至少需要Windows Server 2019以及更后

**Comment by Yukiriri** [comment]
我会将这个情况补充到md文档中，感谢

**Comment by Yukiriri** [comment]
如果更新Windows Server版本后遇到新问题，欢迎回复

**Comment by Yukiriri** [comment]
md文档已补充完成，请按照md文档的说明，把GC参数填写为gc8即可在老版本系统运行；如果遇到新问题，欢迎追复

**Comment by Aokye** [comment]
> md文档已补充完成，请按照md文档的说明，把GC参数填写为gc8即可在老版本系统运行；如果遇到新问题，欢迎追复

好的，感谢解答
