### ISSUE TITLE
在ubuntu24.04下无法启动一些服务端核心

### ISSUE THREAD

**Issue by Debu645** [Yukiriri/OMCF#4]
![QQ20241114-152600](https://github.com/user-attachments/assets/2c4cc08f-e967-404a-bdc7-d7c86ef533f5)

**Comment by Debu645** [comment]
![image](https://github.com/user-attachments/assets/b8c92f37-a254-4a8a-a8f7-35d8717a252e)
这个是arclight核心

**Comment by Yukiriri** [comment]
实在抱歉，这是我的低级错误。现在已经将linux脚本修复，请更新。
